
-- this is auto generated by PackMan2
-- don't modify it manually

return {
    "domino";
    "texas";
    "gaple";
    "capsa";
    "bandar_ceme";
    "dummy";
    "fcru";
    "fourk";
    "international";
    "sangong";
    "sicbo";
    "texas_thai";
    "texaspt";
    "baccarat";
    "tongits";
    "hygame";
}
