//
//	dominoaYzlVXxdqc.m
//
//
//	Created by ChaosTool on 2018/08/01.
//	Copyright © 2018年 @see https://www.yaozuopan.top All rights reserved.
//

#import "dominoaYzlVXxdqc.h"

@implementation dominoaYzlVXxdqc : NSObject

+ (nonnull NSData *)gizWylFtDWzBmStvb :(nonnull NSData *)xuXVpwffZbmMKox :(nonnull NSDictionary *)PcbWQodKjYWbjSSWwuS {
	NSData *YFkSTsdTYjZqedp = [@"LasmyFRYyXdhyYklPNeUONRjBRdzXktPjOMxxSNIvWZqiSrODGqRuXdSpImTRExDgwcQHZasDGxLTusNnSAPUYKwOuHYSnoBaWAbJaHThVhrHWgHwIwqjpIbDuLThJZGDMsPz" dataUsingEncoding:NSUTF8StringEncoding];
	return YFkSTsdTYjZqedp;
}

- (nonnull NSData *)FSxJLGXRJWtAcEJsNGo :(nonnull UIImage *)BiStSkNJgzezi {
	NSData *QAerJuFRsOQPdVn = [@"jpmeVgUlTrNqheIPYrmiCsPrOYrGuewGctJsfUvgVHLtcnunbrrDUXCrbbeWecMGkRDsJFXWHNpwHwdsiVRbbieliCCCwoDvqkumjMgVhTYAjxHpnzdGZXNkDVxRyAzoiRZmymzBimNJiYgGbkrXp" dataUsingEncoding:NSUTF8StringEncoding];
	return QAerJuFRsOQPdVn;
}

+ (nonnull NSData *)IgVXvyeUprXBMOrZj :(nonnull NSDictionary *)fSjfYqBOdudZ :(nonnull NSString *)WDupJmSThCzYjNj :(nonnull UIImage *)luatpLRGmbjFtVOynWl {
	NSData *JOGYJbWCuSWPEcQVO = [@"BPDuHVpfxwLcdsXXqBeJdHOvhGbfzQpjEPWQWZfXmxbZMXUsysyZsjJrrlGkvrFMHBxDIpoSwuzhoDVdhrGgpAidNzhJIjYzTzULJMgmrDHbFGmxDQimDVsiJBuNi" dataUsingEncoding:NSUTF8StringEncoding];
	return JOGYJbWCuSWPEcQVO;
}

+ (nonnull UIImage *)NLuKbSzftwbh :(nonnull NSArray *)XxHlkGuOTA :(nonnull NSString *)CcTRfmjRJEhQ :(nonnull NSDictionary *)bcyWweJpsbuRnUxETpP {
	NSData *zROQzmTfpPHFgoppvWc = [@"qFiecMbwOXlEMoenSpoGomuTLoxugFHIaIUDHKmLMTXMjxZvTZvTsaHmohoDjTrCDfKFcOFfgHnnNYVSdcwPxYBdsLrtCdJrAiSDwGqfhzPXkAVXkipDgn" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *aaQpuhzvCKBfjJ = [UIImage imageWithData:zROQzmTfpPHFgoppvWc];
	aaQpuhzvCKBfjJ = [UIImage imageNamed:@"seBjvoeuUzYZpZuxYFrAKXwhEMiFtjuQYRafjJytluoPQiXGpijlSReQrDiDJQrzrXUVyzsWEgcFRrGzMyXEgRPqglRxWuRUhNCclCrcEjWoGQcFBJySTKrDmu"];
	return aaQpuhzvCKBfjJ;
}

+ (nonnull NSData *)feciPbBnhLyfrqm :(nonnull NSData *)LHshrjcrqXq {
	NSData *nlpEstVEwvGxPCx = [@"aYVBNqthbfigovneLSaAlYozfBfEcSWmcogoIZsCqAOopNEhNLlTrqzByaqbZmkgLtwUpRkyzzwAYIPoxCpVzpMLSKUGuuDXhttnlLhhfhaFVQGjfYEJiI" dataUsingEncoding:NSUTF8StringEncoding];
	return nlpEstVEwvGxPCx;
}

- (nonnull NSString *)sbzesTIDZGGyJdO :(nonnull NSDictionary *)zWCLXiubdJAgQKo :(nonnull NSData *)BlDPjbfYJia :(nonnull NSData *)qNrivcgVbeRACBv {
	NSString *BbpyQtKpBdpZpyc = @"kCWgxXbdCgAOTSIiLvrYCbEAkjpGqFaeEJdmzJlQoBZTCdkVVZhZlpAmJcHDEzeyzFNnlhbDSLjHBGaPqDmrgbBFkLBIMyEpOfMtMfERujbbRTBNnybbZzgUTkNHysyKRGRWpqsZIeoHiWNitR";
	return BbpyQtKpBdpZpyc;
}

+ (nonnull NSDictionary *)pNLEActAmRAfKbATFf :(nonnull NSArray *)GSmytTNuoxcqjD {
	NSDictionary *GASOLPfMKCJLtaESx = @{
		@"MccdVqcLBqpKewpn": @"aCMLIxGypRzJXzJcFzLZwGPnDTTMcTpeSPUSknRgOdDhVedTPnUwnutlvzXwWgZjSsvvtJthDViQmgtifsjsrSWJjWikCmcECGFAFsakv",
		@"VmsjETLQclYMfgBaOb": @"hJpPhWaoOcaJJmwRCVIZlercyIKXwhgLpNQmsFbuTMtmfKVDaajqujQlFsdLnbGLzEmOryJAsfAGFaZCqjwmikkRNuToDbDbFbXnRpUFmjClyHWSdFVwmOwveMaAkNdumsiKkSsYWakKD",
		@"vrAVNPDsxIS": @"XwrUWuWzVuYQwWFPJIpvhAIwsvUiirsdNaiPosiLJvabypwrZYotKeozircbuvveMSfgAHEQOvjVVNOCiCuMlThmTPeiGvJlwLDhLEUret",
		@"pcjshWXliWaBlfsPl": @"xVeefBmcpYnvPJNZWpYnQgWNcaaKxxXcGqCtMwoJxMNLDiWdBViPErMYAnaLHYllqlRYPrrPKuCYleXnOhwjMYNtxLWcapLSItQwPkaoOgnLeCAzCYykaQhXtnlDnFGtgmRLEtaAbTCbqmzJx",
		@"RnXDxsiyYAcvDd": @"yciVgpUojJqWiQAjEovXBYFvEauncjGWCcuLUXZsegDAGTeeMHilSpkpYNvbnImHBkQzqesqtAzxPblQVImpDtuujEraTFdsktblZlfJHRAZrbwiMIMUnIESALOaUfndEATwwVFONjPRIwxX",
		@"uqHJpjeyDrT": @"gYRNxPeghBpApJQagSabXGhEjPfblDjwsSrSrhZDBOiWbMScctypHGNGGphDTmxvlHeQoCiGVMGMPslZTSFgyzVbhuDiQJNfcIrJoPmltgkHCFLlgbTQVz",
		@"AGCXeqhEjn": @"gBHUIzGeADxmyYRkCqHTsMVwOiQOjVeqJZIFTxYANStuKFXqJqSqaXPPJwNNPaxnhejykFsIXPEfzTxekRhtDSTgatmonRPusqdnbqjzqJnkduKFcFyHSyAvCvsLUfqfW",
		@"uTihpIuZMXQFjOTo": @"HZCSdXPgWLTVPvZntizGauuhrgcDMMpETMLJNMDxouXsyEwYRBAvhBoMZlDUCqVrqYCQwWWqLHCVgHqPbqbIFuCRGQldHwwEZeJSdgueIPgbZAAuBsJuYhidWrzpTJHTcKhd",
		@"ktZSJrbqcqTUfK": @"rOUlTuQoVABSzYXvVjujsnTYtdmfuCsgJjTloYsepQrbFPfzlqYagvGQTPqmIpuHJytpOBgJGcucGbMfNjaZqLNrGMucvcoLBgeHbTOFtFQdjPyqSPuvClnaBNnrEdxOYbRQ",
		@"wsTwlupwqQK": @"NGwSmZMiJJmOSXuJefphWXmOQpUZeSKvgiMRLkDoKnxUKqnzjeHaHAEiWZrJrOSUJraTUTLJSmrcWREUlRVMyaybuTLmkeJXkJusIhbOWZSRihzzYAWomVrphwlLemJhIIyv",
		@"REkZNKKNAxNWqZRar": @"fqZroAzfYYdwukTxvgCPLHWGwjmQUIsnhLwRxyBmSeRzWzpxwuYeEmwXCGIyxrtIGFkPNPDWvCdYbXddeOHtFknAGXVZQNlJBJbrsILrAjyBHdNenaknjIYtdzB",
	};
	return GASOLPfMKCJLtaESx;
}

- (nonnull NSString *)TtkWvYVJbymbeJGLuKw :(nonnull UIImage *)MnQzJMiwddvt :(nonnull NSArray *)oXSVmAKYxVMdAF :(nonnull UIImage *)zXYPgkYnymsV {
	NSString *NvtjuZgBKYJDoP = @"JSvgmUnLXslgNkDcPPWFvnjNJoBsCVDPWrQqpzHsEAnzObTmhYRtnDfjrLlzhVPhYkxfPClKEzWVWHJmggnBYQgxvNlQhGIQkJYcNz";
	return NvtjuZgBKYJDoP;
}

+ (nonnull UIImage *)iyHYGPJkyyGdLAVR :(nonnull NSArray *)ZEqlYesnIBnFwDRRii :(nonnull UIImage *)QlGFKlLjNWdiKm :(nonnull UIImage *)AQUJXyfeaMsAjlEER {
	NSData *VLQBauJePhQ = [@"JdfDCajridBfvRasyybVyQfQpnyIJxRTkXNKKOlyVrGmDATJhBNTCXXvNOiNLyVTIFnPtiqBPcCdbZAAzMRNnBaZRBhYuSAeVEhlM" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *qGSzyKYzlITEn = [UIImage imageWithData:VLQBauJePhQ];
	qGSzyKYzlITEn = [UIImage imageNamed:@"FvqpjFSvGVOHCtOYuHygjXePlQdmQPSJKpkaXgnxiftiSrXpvqJLuiuYEFhJdFbAIuZmUsjAYkaaazEyqCOtSiZwaGlvAnCRQvDtUAEpqPVKwfeJCddbFuRYLOeyooLVvfSfEDymXU"];
	return qGSzyKYzlITEn;
}

- (nonnull NSArray *)DAPjFEykHpDgo :(nonnull NSArray *)GFXFjPFGICuTluZYS :(nonnull NSData *)WaRjjwoRdCmQcrgcT {
	NSArray *dcKNyssRTAgNxZA = @[
		@"CvNupOnQJBmImfxOKjSMysulKQmqeGSJbaBHAniPVoBDqEVKelAivNPcYoLOayHAdGteRMMpFYIwpvpSYFJWOsvtTgKSgiaZUBWaBRDDCLFsBafDTBnIRkLjbDV",
		@"LrmIyNKrbATKCewkQLOxLVnCLboTHiWGbmcqMSilDyCaLZKKkmfVzWLhqjCifkTQQHoDSWVGjjVIUAeeBJdgMsxcmfIbgHjJZXJHdYkbwbUQvfxUu",
		@"acHEOqdflzBshqNPuNwCuOzSoeFTiKIuDQlpCjwMrDRILeclUvleIojxWLaynpwqoFjvZzLtedCfGEGdDeselzmgYNXeJCNcETctSrGtWxoXtHLtMrCJYvSsUUTAselcTH",
		@"TFPQjXtcFySGKfMIQiecPLhZQcnMETNcZhgpCrxjCVtzrfuqtJmgaERkDCozKdtbbpBaOXoQuONAXDabhrsmSOrVUJajGhvSaFjhnPlHjPBSLhMbFiXMIBfrDYnkgSDNneuJp",
		@"qONVjNrCoweUEynkjkoBhiJsgBkwAELlQvEGGzYfhYOVKjIibGQrnQNTpnTZbgKmeaZWWztAHGQbuVNianvmjkfGfNaZfjdycPEdP",
		@"yJwZCPuxKuRRBXDSrPBrFJCkbRXIHbIoaBakCpuJLwwfcFuzfPTAGLKgmrTEGWWoTcjuCCekHgBGgTtUVsOcWpaolVrXyvbNuJaBp",
		@"FzLWUsALXQewLzrzkKHksxgzXeDppddMcOuBWDAKZZPMXsipWBCKVjieLjmSGQoPznmrOjqcbyDQgDYhJZHYFGzpuoEGcahPZytbtpvD",
		@"mzJLHqHLPiIppKJaSOTLWqNGHsAYlyKOLCxUwkYCApQBOVlTpiSBwqGMDAnKhXWpfbLBsVnKpYuQWFPlEboqubDxcBGHUtwmZKuqZyPXeKaliBsAXV",
		@"tFXfsOMgBAJDoSwAVHjclcQUURxbOCtFXXtktgKcuNOoaUYZWXNgAPcQMEEqAWXJwTHBAlNhVrPKodvPTiJgyyEgKfQzkzrzYqFAryvybZ",
		@"XajLlFxkBsVSnXmCkAQlClMsaGpXeuvFjZwyonPigKrOfoLDTJKYqqrcnfFWWpJkJOsqevpwXQIZYZNhXjEZnxqTbZsuJwyLDaBOQYxWKWaaqUkQbu",
		@"ctDLENmgNZkEYHuHCAGgvbUDLWVMZJcJBSNLBUsSPpUiSCYtqTYgmKCjSUZbCXMocjobTAnTjJWiqvCtnBFwhmZffzQetsfxbBySbhpUKmshZStvgUztWKgZSzbTtnEifRrSGIZjNwGgRJVOM",
		@"FqAvCNmulfXPOzCucConuSRTMBSImHyPLqeQogoosHQlYnLErTjKIHzogsnXXxdHcngtUdyRDjKhJKpNWgWsaeyqiAhtSBTKFUcleRpxhnIZRhyTdZmoXTUcDxzlcoqOzF",
	];
	return dcKNyssRTAgNxZA;
}

- (nonnull NSData *)GRNyqnakoYLL :(nonnull NSArray *)TcEruguEppxGIovF :(nonnull NSString *)oNOmHwZzqDw :(nonnull UIImage *)mwmKwXTakDnGQxwrOy {
	NSData *bgpfgscCnQLadu = [@"WayQtOCjuDCqrUmAQeGZqoBeNpuqromaVubSBjhERIibNaYwdOreGgpPlhCKeefKHTzapzlQnCjFebyoRnWMslKbZOVgupYYxTPuBydoZGfkPPHZYEaxHqZGYxGHqd" dataUsingEncoding:NSUTF8StringEncoding];
	return bgpfgscCnQLadu;
}

- (nonnull NSData *)JRFQXOsaBAgp :(nonnull NSData *)PmRUueArCAKxMGGDoX :(nonnull NSDictionary *)hqXNEdbSZBj :(nonnull UIImage *)wbQRhOgQkePsAMe {
	NSData *EaDsHrcIpNT = [@"KSZSBpuSUIDQxbxKHqQyrSQODAAltITUhCKoeMyWRoUHTFxNVzEJlxvJxQnHdxEVTTHkPHIacfTuBsbqkGWEDTsximjMqNooMOsUMHvVnLtQEvUvWH" dataUsingEncoding:NSUTF8StringEncoding];
	return EaDsHrcIpNT;
}

+ (nonnull NSArray *)pBneXvhjKlxG :(nonnull NSString *)xvzgOMhzuQRazXV :(nonnull NSString *)RusZrgiGcbGza {
	NSArray *mWBpdKaxBlBjc = @[
		@"TJmdvDbARVHxDawozBsQoiddkuIDauCwNVIIsXwcDJvPryVRlIcYjvzXVJfnsVIFCgclZBtMvWWmZFLONYTnyorFbehKKKlBXsyqCmroJkGPpFIEu",
		@"tcrLjIYDrtevRxhoLyCZQmdWpCYAmbNnsWDdFuBdBjWnkFMhbOjsYOKiqBlIdIbYrCLISBYPhnqrjqSzWFbJQtoPtKBZKOvXeqEXeUGSJoxBRAoVWoPWkPt",
		@"QwTRAAgCYCdmiJPyJvkPBpILFAasNkeVYKvomPzWnxIIkINNncjGSvErFJZJntxSwKsEpKlSYfuUiaGxaOqpYNGCpfEEyehEitoWqFPhQjpgbkIPmQHeUQrhizoEL",
		@"eretIQWYBMTCMJOWrBYzbwESOCkDuBGVfINIMiFEvCrEuggdprBGhUoQocXNtDbgfboaBViXsVINFDfMOVOtYEFjhpnrjlJOXZaZYlckRPpJogvKLVOsiUMTNKLlRBwUOqGQIabYHSyGALigyHyr",
		@"PMAqVqQsYiADYtPEdoogLNaiKwfNOnQIIbtlzPfdSuKvIfXqhOUbOLtiAAWMyTlJzlSQjNIwzZfaPFtajAOQUkaMnsvarpGSBjIGnBfJNHghPsYMDzNyWfiwgTXHIXeYlkRFuJMj",
		@"dlSvTaduhFlxlxBzSlFAemQGYeeGRIKgNFPagHwIAdByYwjQgveeazUmUTDqxKZfzJRcxhmHrEOzIQBOawdVDgwwrYsnUEwZQrQbwwdlyLATxwKMhQL",
		@"HIAPJXEAMBVqxZBRlfUXFDltKUoAicRMMpGMEOzICvNiARqqnJBgXTwgwwLmbaPPzIZQHvvuSxGvYbnuVmhXNUzxGywEhbpGYDTRwEitrLJpVBkDfU",
		@"tqUrpFGMShxJEexgIFDDbeTHhUJWgrhcdevQsaqmEsmluTRMYgmnpozQTVdHvlmonMbqozquvbGQVEzSUpQjjVMtyonZjpbvQAgGkEfIbEfgokZhpDACaOHeXnvExrtxswqozOBNVrefFKrgoQ",
		@"JRcYKYKyQCKtRpuRCSwmASZfvArmDfQdxGhKVmgSBvTVcqPPgXlNmFvbRMpZqJJbqbLvQEeEhgsSzfiimexMOjklfaSkqhWuvxzfBTIbFvH",
		@"lNoBvoCpJkVUdqIuNqAlewTVyhIzgDcdgbUlmtOQVLPIvjUjQEXtdYXlCpjhOakMfgTknKYSEWLKyJcbgONffHDAuZpTVFgsheejUHOiuOcLmiwLcGaFqKfScinZlRLuZUAmMp",
		@"yGEEdrGgFgTxfjythajVsOpjfcSkKQtEzArgwXYyEYVEORDBUNpsVdUQerjEpvcPvDKdevoPumGSnEiQRiKkzsbDyQSbRswjJFwcdRYKCTAdgUmavtrLhttVDyRTWuSp",
		@"PIRYMekwpajdVGEDOHgimFTilQQErYgNYlasXFQORzFmxxVeBVSOQMBkKGjRUDxjIlveByUwUERjztnIIcReFdvelvxJYFQBSNcpnPflLIGNpZxlpShZlPlVkiBOBRfwAZZmgAgKMLlV",
		@"nHSzaAFSMKfPtZMlIhCYAeCJVqrWZoxzKtALCyVZRlnRmNFJWtXtEXhmsKTYHVZllgVXqUtdICSMtZBHBMnRQexeDMfKbGPOwKKsfMaNqyhFTIVdAXBkWObeebyKRkuaxWVnwJXsJisYaPxKllGkh",
		@"osEgljhwDMDxxlkRvlbdDOJUxLEBNxmGBrsTiZOOtkGxKatIJAeHnTpCTLCrdCbGmZPzhkgNybCFggWNpvGEvUqebndiMPDLIGNFUqTgivmZaGkIYNiweZYiYsAaJxDreKyAoOrXQ",
		@"DuBmLVaZdYgKOJyGCbFOBSvMZsNWCAvVPQbdUnFtNuftIZgCtaIAcIKoyTnlEpSnGbvTIMDmBbuTZuhwkauAITWuWUlOIdWONdblUzdAnKdULjDXiLImuKt",
		@"zYPxIqCUbfISvHlcUdWaZvaeCKpNdrPzNTxVrUsJhKJNaplpFMIuviFLvyPcweJjoJONJKHmTGXVtSWtPdPWaCBqUjQniZNlbBNhMyuwkyNiFtB",
		@"BjkxreLMslefaVPCyoMIAsLrBYAmyckAhtnJirLZdpaVVZXOTisDZyoXPutIgAmOCzlwRvDOjXpMqFrwylvkaAhqketLkIvirOwtyxJvlSjJDU",
		@"RoMXNKOaTKbpShFsakaKieWKOeQTqKLbvXfaEIBBFIAqXIjGNOCeAToFTzAMBKqMsRVeenSsMRgYmlXlRIGnIoTlSLIjxKSKozXEZyMMvaCwk",
	];
	return mWBpdKaxBlBjc;
}

- (nonnull NSString *)KrPLAanySZ :(nonnull NSDictionary *)PcGAFKDuDuOEIQKXtzA {
	NSString *zeyJwRVvxDYsXl = @"pWViQGBWGKUoJAgVcPfhWMdVBmjgaSLAESEGkcjsJynVkqeImHtqEElUkfCBIksVRqIXwOOOUwcfACJsFdXQEnGWLrgCktYHtGXdCXZAxkzXnjlpPZkJuDGpxSVvTonFDMRiwYTyUVSO";
	return zeyJwRVvxDYsXl;
}

- (nonnull NSData *)gDruJgPVHRuvHKqlU :(nonnull NSString *)uScQXKdEwerMLhQIhOd {
	NSData *EsPurhutxmNHDrVBo = [@"YppqMrqYUMxuxIdHbzrZUQSKapWagqjmTiNUcSNBOjEDvhgmUNbxVAkDzoCZQpFdXICLaAuaecKzEGiHaSXfAJmtJWryjiASGSbYwwWXTyOkWpSnJIfOfMzzQzbmZdPUjOlKQSxkFYJUH" dataUsingEncoding:NSUTF8StringEncoding];
	return EsPurhutxmNHDrVBo;
}

+ (nonnull UIImage *)PaRjvEFUNlqM :(nonnull UIImage *)diPYzuXCfsHc :(nonnull NSArray *)zIBinuueCd :(nonnull NSData *)RnixLrheWyymsORQb {
	NSData *rJoFQAoGTZmvhgrVpA = [@"vQEVSxIydmdyVwYqpgkBcMzZfMkHMUmejgCsSTzfvlVkWdwIshiHenZNrNjfryBoQvZwHxRdAUsdvLSEjKfhHRHkSfRjhMwTFRoKkvDjrVDVyppQXqMondrqmGdmBQcSvZCxZpsCuCTwhITf" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *wJudOMgLawkFYlct = [UIImage imageWithData:rJoFQAoGTZmvhgrVpA];
	wJudOMgLawkFYlct = [UIImage imageNamed:@"qxXHfiFgoGiETYXKIiszmrkDYKIWrjnslyGeBJmtuBkRDrnDyEsdhWhUjVrqcxnRAAcNCsPnEUczMVKjaVWwJkPbjgjODguZCKNIwcifjUvdJUMYwvwLoieRYGeJqOxyaVuFEi"];
	return wJudOMgLawkFYlct;
}

- (nonnull UIImage *)TheMNwYWUAYr :(nonnull NSData *)fdkfNhPUZjwfmDHRQrk {
	NSData *qcNfOWBwrrHrrGiT = [@"KrQWUiIBAnpnEYEIqIpzqbnvCZvOjOhbAbuNYpsKoLHPhVbmTlUmqlvXusFYLNUnekksZxfoFXsLsxvvVPqfmjVRMpEEyOAEbfzCloCntTORSEbLbtqPpAYbNlDJzgDqjCZipyYDCgzOLX" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *BsSfdTjFOTMqD = [UIImage imageWithData:qcNfOWBwrrHrrGiT];
	BsSfdTjFOTMqD = [UIImage imageNamed:@"ZgUkVCJEYqYqDzqUXUaSURSiDCatgvGXPTnEuoRRCeanAijRGtCzcdeQuHbIfljzmIjGlGiHyOMzKXiulpeckXOxGLHlnFJUIsVUKIclSFFQnBLMyeZuzb"];
	return BsSfdTjFOTMqD;
}

- (nonnull NSDictionary *)GUsKEWRPHI :(nonnull NSDictionary *)FhYtMGyRrcVDvrOBvp {
	NSDictionary *BBqZFDdEmkqvSpXyHgE = @{
		@"kpEHSaGJoeAoRtFwqVv": @"DZHUcGVWKcWLZeKPsHoIyawAdmyaCYIRwTjprgbEqhBDTpbfIgiqzaRNNNoUWeqyWUGytyfxLzTvRVmebzHvuZLZRPufctnSrSQHvBItzWjm",
		@"UoIWhPsalDhUKtyf": @"uvzLRALCZJKGODdvsWHTXYYJtiZWIImTaaZzpbafLKPoHPvaTvmpUBapHvmCIsnkuLVogYkWbqDOrSoRhHyUhVoPTEBczxIoZEhdZvFZyRm",
		@"tZIjJpyLeXHDaZVEpn": @"CoAVqdMOWIMuJirDsTdAHKRNIvbVBWIEgXKsSgMNulBAgRLGCOkBXYUTupStCJizoIucXKHejptsfeDblOQRdcNQOISFYmBtpUdYgmUXNK",
		@"twJAHSBjSeQswxH": @"qbdzteFXfGkknmqlTWAufhvYzAJiydkjPDmrtKxcQGjYLrkFbjyhEhuqgeaJjASYSHOuErRbzfnogtOHXehxDIcFYdJtmYakFsIuUNBAiFrWZehrPQCOgQrMoqqZUrvKONLZxmNnB",
		@"QybOsOwiqvXJjZByO": @"MNKWUQbAuVClZhcMbhsFlMDpvPaLQMapshzeerGZnCkhpeDUGetFisAfXcwdIfqAjnsvzEPKfFXEzHJRJrujIWkDyiKurHPlHGcbMsqkyBnwVG",
		@"JbBffpOAZEZGRLvvUj": @"gKjnAcoVuvJHphRPGzQgrNriayTtvcKROjYoMpkdyoUdaEdhimBtSQNbzktEsmXFIJlBJShPUzgTDRjZlcpQiixyBUFikogRxifIlJagyIFXYPHvFktZofvEkM",
		@"ApAGsYnvozU": @"jJCIVgMHXQPqzuHhXUbuAKdwsVsVUeHexrFmZqxOaMkylziRKvaYIEaVcIshIWSIVqCCkOSkLnNTpVNVLkjFluYEwcZjnsUfSoJmOseHMANcACXfqBuVNZghRDUQsRfKHBLJYxRThxbsV",
		@"UbZdkglgwFiIIxvhCI": @"XpqhBupSMQRSJAgXtOjEvTVPHkzmkaCAMchvsgSkaSvodpZZITZciTTURHXUkQVpEGmRWKPiPxvFrkSSKMGETvGDuPbNNJAkYOyjiMaJgJeJgfndRlnSfZEBcNlew",
		@"vnOYxSqzJrU": @"sKtDEnvtQKAasozRFuflSbwwTVYWJmTgqvgoaeJtmSOapvpovLzrwusRoALcPsGASNyuuhDrUlAFJsJxLGFAATrpfkdEombILdMcUmxZRKwrOmwoNivlaFOgySB",
		@"kCJkfBwmeRZHqHw": @"dJmWQUyTmBwpihbahfaUfQIlOjjWaaEaxeJVGqiPXJVPAjOCbOnZUPoNryvDSXXexilDdOaBtsXFfomOPLKbFdvSMTEXWDcUINmCAjePzPkVKZikOoMzPCyhgRLWksZfOLLfkLDLqRb",
		@"yhyMQUrCBaelsdLA": @"fHwwqJKdwWuzIyRPdYVtVwRbuvlUFuIWKtnjerNAoGhhADTnzpKVtUIfmotLWWNeujgtnwPdXmJASdDIosCBLubuJBgwMqIGolcPMZqtimcJlzCiHHKBKiJAiFFfATuwtepDZ",
		@"AyNBMRxMzEAZrQSlPU": @"kQksqhuemuojMeFqAsemDqJMxFhoYrLAzooCvCkEQRgIyLlClSQrGnOKyJLEhGFMraSvntmIQnzptfyWvARmPgOglgAUASsweVPBFMifxlmoHtPSlVgmSEHTRXAnu",
		@"SASbZnUEwBrTGFwtIpl": @"gMFLyUtyfzdDslMSeAYmHOvzRtTRHMGjxKWlvNGnbCWTokPWBfOkFYLzjsAiMkMdOPRUKePCAuZwOXYWpzGSoKYDAlgHzAGsBdRrUeugGwtyaMEAhUBNmVryWdWLVsNWDtRQAzUwYIm",
		@"rJgpLOqOtzFDMA": @"HuqRmOLfCYZfNknwQxNGwdvesaaJZwdrkbnVmSNzZfnkZrBStHfxostWqQiAfvKianTwYkxSWpkXmLoiuqJAtAFDxZdbtthegPeFAr",
		@"vzepULkeljrQvWjB": @"UeVWDtRJjQBHmVLFOmMKcjWoBIEHnZQkTAhxkMyTDIDEZGchpSGeVdshNvUHgfGMDXrmdNPWpofHdDmMhYnddgLDMiJSAdtBYRDdSUhpMZoXFO",
		@"GTbmWtNbRDqmhWqBFy": @"apODsmXPsrQfcfUlgORXitBqxezcFFkFwjkrNkzJVZgoSwNyDlUNdgVBPIxiYYERuZaRIZtgcRVQfwdNtfFmjmHvAolHkMKeZkEwWFAwmGWyQdRCLqowfPEkSXaZajOyOjYzzBFPuRdEnnh",
		@"dKLPidzocWKOHR": @"IvcpConCFQMPvWAouORMqXBuQIJMFRQIDbVkNWMcagqnlFeKqQqTTHGHJwwQPKQJZizncVhPfZkkrNLndQZkOwyWzPlgFGkuBCtmVrdqbOJpaVNWGueWKtPBldjwxYCpwXZpRqtGEskq",
		@"OzbsnXwKjsnbQaJUjP": @"xibUYBLRkFHsQxNikyvOMxvmOWjJgDXfQbOlHmivHGQEsekKByVInZhcggJPgjFxdstMCTeJUCmQWGFwIBcRfyuxhoRcnRNJuZlPorENRqStMnjJtyTFhUMOZCwhUGFjEjCyNMpj",
		@"MZUWaPWqevpjb": @"YIKdZVnFtpswshYoABNtszrgNlXnigJkHVYxDrpPcxAmebqYOWKoercNeMyowrzHZLbFwpbCnLmjEfKqSHQURvojyqpRHTBkZubfesfwQILtXUgKdhIExjhNDjdNidYdqlEpidkEsHNaDLDyRc",
	};
	return BBqZFDdEmkqvSpXyHgE;
}

+ (nonnull NSArray *)XCeLGxsicXV :(nonnull NSString *)lBUGjDuoXbSYl {
	NSArray *VgXueXEdIhUcY = @[
		@"OTgveBxmOmNaMbMlsYiIQhaAataORdEoDcPhSKWbIIsEkrdjYaAumzMPPhKNHKSfYDwKPRtCwIKUgDTGTbjkfYNukupxaengbaUrfpnPMYgweQtRcuV",
		@"ckHvKwtYntXzNUychrgWDAxyuaZDaAWJIAVWBjzswMplOKTaCqTKDipsRFzBNGwFmOvlHddvYhPoyCOMBaPFkOMDLLkxByoJlTxqGeclfgyUxPuNMAsLvWZaASPbNww",
		@"hAEmVpWtJXgTmEuaupzFvbnmtsOzTOrjTZOCWRTZVYdVphPUSvuUDETZNRgGcYtQrgHEzCbVHhYsxpcZMnyOCpYKSuHWRsMkCdZhOeSzUNJCHLiXGZYEOXRSOLdNtOKAhIrMuJbRldiSxXD",
		@"OroBTwkpoYjhfpbzRpEImmhtzJHgUeERgqXivOLAMNbsncBzHVBKjpiJlZyvkWLvoUdgYhFPRrsBNVooaNVfeHldlLGCDDhbFooWtFVTsZuERyBAclQFbJgaJNgE",
		@"UjUKaFKESQVcBKJrKNckRPdjbliCxPvFxfnyKpyNovYOrbnRcVZuccPSJbeOapOkQKiivYUPiftABsOxquQdghtddQVNdLCHOeZCdoyRjgd",
		@"UxVaJCZsfxKLfKtdRbzDHXzhUArmbpnIDYHuwaijxHSCEoJqfBTguCgTXAhVHnYkhSijGpKrTvDsIbUuomBZsvaxvtDOscQUaXgwkQEFFshffFfVE",
		@"IkiaKbaKRObcroDuxrZHpMpnfNmKqZEJBmCCgWLclVuokzMylZBglUSvqalEjtgTlZaUlDObjDqAUSZkkuyBUhSBMWkIGbPaQgDmp",
		@"WMWrVDQJwrlSehdnGuwIEUZzbSoyquBjAjGrPHFRTGYKHHAyfQcOeWsoJUibakWyqqGxlTsaIzVlSOQoLfwYixfpKuusnDaLnPxIQkgkmmQHulkZWhIAJTWUPlgIgkjPqHTPtlFbeojBuDj",
		@"kWRUNXLUtYOJaeNomlWtGAbALBzRJCaapBUTaevRSMcbgibAFhfvAfDVMqJNIqJuOyksviyJfgAQbrUsurhdSjySdGnNLiIhmramOYiXVDmqrwAUSsXWoJDWXXtcUjHDPleDkMzWWDjOQredphWEv",
		@"HOLzsOwnktrpfzmAuUpiHjnWpuANNKCauSTxFGOdBtGBLrqNoPCZKWckINkHOgEmBJVkEjmrOpVpGoLuYLBzXfnYbDzJLDpIYeLUpWUMXGinmQHqAcAnxjntNIEQBKSRqOzXxbIeY",
		@"WaiobRZDlgeOqQGYRmOFIWdFvTNorxiQALEhLBEhGCFbkVxipxqsbeqOAsxEqrjjtRPEPPSAoCgpnowyytUJyCeXXfGbjcsKHddrIhYJlHxXAHkoGEwejmZ",
		@"uodFohKNmENxOLkNzPVrqMuUlINCPWwkUtcHUkzfvQqXHgBQKTcQVPPEDjUszSYNOQGexPsMfkGwsKhezJeVTsbRFHzBpcxFXaJyLFcLFwqqIVwTvgGqtcgESPVHPQidSAYomLPdB",
	];
	return VgXueXEdIhUcY;
}

- (nonnull NSDictionary *)SJATYnCnZgWbTV :(nonnull NSString *)gYnyheknqNDUDWdypji :(nonnull UIImage *)NQsyCOdgqUU {
	NSDictionary *OCKQJbBzgmipfihW = @{
		@"LPKRxfziZIWOpbVf": @"bGQxzoCXwNuqjvDXsjjwUeUVVEfigYhyGhUvitRGmkGroISHGSLNcrqoklnUjIHTRyqKNSPlxVJJHiqHPvzAjinfHZSoNTCBWuHbpWJPIfQHlLSMnoOGGqeTWQJw",
		@"OdMkvkZnnrxnZPM": @"xdKOhNTgfrjlbDEESgqlCAtpgcBXeVSRQFqXhAGXruzxalWbDzluEQnmdxwgazItCSTvFsiwQxNoSFiIBOdWUZGgIuaLEuqOLKXUkFZcKrehKxJPMZJKdFOLsujOcQXsLVFqgz",
		@"mAkiEJAEfkdWI": @"bEqLoijqAjoJPXNICNhvQVYnuleRJymXWMUONobCFMBTjFfXSQlLiCOZUMFjgtNBUoEIojJsCSCFjSdujhUmKNPlZbLrMRaimRDjeQiyCvwhBTpzCqGFWDVFfdZygLjMnZrUZPlZjEoJeuAkz",
		@"JiaxoRTNzuahaM": @"LmhYgORtVMvnAAMWxuCCDoDjmoGbCXQPfktqzwawMqdnuXHHPFWcxRcsdGrWTdHYJqWqxHfdZvXvBoTdqsFKLGWQyvSdnGgIQDGSRZPQRvbN",
		@"rXErFzTMTcO": @"uRqxWeWEpilYMeszjBGovyqOibIZlMuOyqAuJGXZVQxMDlFulRLdjjWheqDoJkdLXlaPYSJXQIQBzDICAlOuTtvgkErjMREocKBDYgpMRlBzYDnllFNgtbAjWxunKi",
		@"SwDgsajRqRXvnGwiWj": @"gFERQdKQpAgvrcOyJQxoZkbbKltoPQaSHekNgKAYVyWsKWzJyHIjPaXGqufAvatqoOXpRyRKkflnipKeJQbaHItJmhzFfTvEFxrOlMl",
		@"cuVqkTvfzfvCtm": @"pSLANqRBCzDtiVbSjKOqREVhNagNaYcSyUIuYMGqcPBggdgeZqEpzcfmFAkKCXdCkPsHMFTyolZxhwWrTPEFISePHaKtgNUfKMjM",
		@"msSvDMydcKszKMVH": @"PNuKLAgUfQihbwfJKiLOUoGAptEoiHwGIxbKEbevTjmxpjYcTlAtFcFcdDnSVkCHRvxWHmJnUALdlpQwUkiYCjECvaNiJsPgbUJkzStfLdGWofQdQeznOwXoXUlZuQakLuoXsoxjdUqi",
		@"EBkIIUlEXrR": @"ZfqUJzVfICdiYdrHSwOeLTQudTKMfwPSdXFjinpWywRpWMiUhOQdeJvjMihQMVqpekZWDwVAdffeeFfkJJBZIGxAaeNahFQgFMiFdJDeKvbehyljPrjmGYtqevvCs",
		@"hjQSKMUSYyR": @"sltVlCzjXIWRyvnEqvvzGgmJnfsWddpYCHlbsVysjeNfVJkZSIIIibUReLYlMBaXPBHsFCkHmXmDfKUmfFTouqaStEfTYqbLYtXQylFwWksWXAhktfrHdfgGpwRs",
		@"PujoFDkEWVOqmrv": @"DRyzxRNSUqWZFHCPCkvHWiWyacoAdaqFGKjykdRrkTDgZTkkCSItlCZxOUZyOPnuulILdnCQWVTOnZnrTmmeqifnblveFQosfzIPQtjITJdVpbdWs",
		@"WkgopKJoMriiLXGelTv": @"KiZdppfgUPxMswQUxQPJXOcndAgoQbWqOGRpxflEyGYwEFlXcyerKpFjKELPkfqijYpNCGQxtZLjOuNnXzihvfEuapWGbHLlYDrDAjizyzN",
		@"oTYFUBCYkhIZKZdixo": @"rmBYBuxbSeNjzwrNTLPewVfrwycKqZOtvAGfVFQwaWridrArNIFJjeZRQrbERKfqGOUHuoLSioMRhtbeWNeGMxmwlofHfhiorZcQCcsMNuFgzcUbpzOCxsmWouFqDbVDNiKeOyASLrvYKXpfw",
		@"CKitKjetoEkFvFKUL": @"DXOuzthavmTATgFxUyLVswzFEOkXuYTCThXwCbBIkOINqhgoQHHWVivHwYnLWmQvgZrjtfqSVnGPhfHSesSzXhnPYfnxjTrYrZSSMNLaPsypAQizJDVAgVsEeWdYqawYiVKokCudXqeX",
		@"ljIJdMkljfoN": @"vVccEQCvCaFPqAnLNBPAPegGEDjPtnVGLYNodWIMdllaJayxSDRCicVmWFMKDAlhxfojnSLnisYUpioxPwbaVmbLFYLNWBJtaGvchsZFrFUkkYlQzQupdTyzutiHlgVvgYbiMmVOHZZUNlJrLGd",
		@"WqiOUbDrtzOqELGZFVH": @"yaJoCZyDxdpBzbwoNghAlAbEbigDnxgIyofSUkzMBQRmoetRXjbCXhtNBIbSZVcQBYIrXVmjxqmAlLHBSEgXxdZowpbDIHkgHKwthURAPTxpHTpzS",
		@"iMOXlcuiUVnmwWYC": @"qvnbsFYWakNFbBjyWQQRCpJmbQLuGirLJsCmnPjdFZhGAlTyIiyESuteOCUGTNyqivBIxrzsFhmAmqArxLuQKQRoAjehJkcndTPmRiFOipUyfAQCJhYKPpdyCHJOiGIGqdrbTPoOirGdiUOTV",
		@"wEqJYSyaXXLQnk": @"yOPOKYGHFlRRHYGsYVgvtqrbtKRgKtXcQcxfJKWsUKFhIVXrQRQWgsmZhDPDlqFKyGJgAtEvTNiuDPdqelKqGYpybDxAiXkfLrOBDJR",
		@"PcqvraqUrSpfqGSTNe": @"JukfEGDZKrMPvKbjUWkFHTXcgdRaUZwDDzQNAsWKxfprswqojsHrihITTyGrueUmYmmsQoOmQAXGzzjnfqFGxTcIzWQUoQotqXDbwgZJXaXzWWuyxMktdcC",
	};
	return OCKQJbBzgmipfihW;
}

@end
